// Upload a placeholder/screenshot image to each mod's Nexus Media tab via the logged-in web UI.
// (Nexus v3 API has no media endpoint — this is web-only.)
//
// Source image per mod: media/<key>.png (generated by gen-banners.mjs, or drop a real screenshot
// with the same name to override). Skips mods with no nexusModId or no image file.
//
// Usage:
//   node upload-media.mjs            # all mods that have an image + page
//   node upload-media.mjs DarkerNights   # one mod
//
// Semi-auto: it opens each mod's images edit page and attaches the file via the hidden file input,
// then pauses for you to confirm/caption/set-as-main and save. Press Enter in the terminal for next.
import { chromium } from 'playwright'
import fs from 'node:fs'
import path from 'node:path'
import url from 'node:url'

const HERE = path.dirname(url.fileURLToPath(import.meta.url))
const CFG = JSON.parse(fs.readFileSync(path.join(HERE, 'mods.json'), 'utf8'))
const GAME = CFG.game.slug
const MEDIA = path.join(HERE, 'media')
const only = process.argv[2] || null
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

const ctx = await chromium.launchPersistentContext(path.join(HERE, 'profile'), {
  headless: false, channel: 'chrome',
  viewport: { width: 1500, height: 950 },
  args: ['--disable-blink-features=AutomationControlled'],
})
const page = ctx.pages()[0] || (await ctx.newPage())

const targets = CFG.mods.filter((m) => m.nexusModId && (!only || m.key === only))
for (const mod of targets) {
  const img = path.join(MEDIA, `${mod.key}.png`)
  if (!fs.existsSync(img)) { console.log(`[skip] ${mod.key} — no image at ${img}`); continue }
  console.log(`\n=== ${mod.key} (mod ${mod.nexusModId}) ===`)
  // Mod images management page (logged in). Nexus historically: /<game>/mods/edit/?id=<id>&game_id=...
  // Newer UI exposes an images tab on the mod page. Try a few entry points.
  const urls = [
    `https://www.nexusmods.com/${GAME}/mods/${mod.nexusModId}?tab=images`,
    `https://www.nexusmods.com/${GAME}/mods/edit/?step=images&id=${mod.nexusModId}`,
    `https://www.nexusmods.com/${GAME}/mods/${mod.nexusModId}`,
  ]
  let attached = false
  for (const u of urls) {
    await page.goto(u, { waitUntil: 'domcontentloaded', timeout: 60000 }).catch(() => {})
    if ((await page.title()).includes('Just a moment')) await sleep(15000)
    await sleep(2000)
    // Try to click an "add image / upload" affordance to reveal the file input.
    for (const sel of ['button:has-text("Add media")', 'button:has-text("Upload")', 'a:has-text("Add image")', 'button:has-text("Add image")']) {
      try { await page.locator(sel).first().click({ timeout: 1500 }); await sleep(800); break } catch {}
    }
    const inputs = await page.locator('input[type="file"]').all()
    if (inputs.length) {
      try {
        await inputs[inputs.length - 1].setInputFiles(img)
        console.log(`  ✓ attached ${path.basename(img)} via ${u}`)
        attached = true
        break
      } catch (e) { console.log(`  ✗ setInputFiles failed on ${u}: ${e.message.split('\n')[0]}`) }
    } else {
      console.log(`  ✗ no file input on ${u}`)
    }
  }
  if (!attached) console.log(`  ! attach failed — do it manually in the open browser`)
  console.log('  Review/caption/set-as-main + Save in the browser, then press Enter for next.')
  await new Promise((resolve) => process.stdin.once('data', resolve))
}
console.log('\n[done]')
await ctx.close()
